file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/include" DESTINATION "${CURRENT_PACKAGES_DIR}")
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/webviewConfig.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/webview")
