vcpkg_copy_sources(
    SOURCE_PATH "${CURRENT_PORT_DIR}"
    DESTINATION_PATH "${CURRENT_BUILDTREES_DIR}/src"
)
file(INSTALL "${CURRENT_PORT_DIR}/include" DESTINATION "${CURRENT_PACKAGES_DIR}")
file(INSTALL "${CURRENT_PORT_DIR}/webviewConfig.cmake" DESTINATION "${CURRENT_PACKAGES_DIR}/share/webview")
